api_version = "2026-04"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "bb7489ef-c6c1-e248-1877-53ba09f84421b5468a16"
handle = "esr-product-details-block"
description = "Show client interest and outreach opportunities."

# module: path to the file that contains your extension’s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Block.tsx"
target = "pos.product-details.block.render"
