api_version = "2026-04"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "7a3ea99e-2da9-072c-58d8-2d4799067535366c5a02"
handle = "esr-customer-details-action"
description = "Open the client profile, notes, sizing, and visit actions."

# module: path to the file that contains your extension’s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.tsx"
target = "pos.customer-details.action.render"

# You can omit the menu-item target and POS will provide a default menu item for this extension.
# The menu item will present the action target on click.
# This template has the same behavior as the POS-provided default, but is included for completeness.
[[extensions.targeting]]
module = "./src/MenuItem.tsx"
target = "pos.customer-details.action.menu-item.render"
