api_version = "2026-01"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "2c5bd9ba-e889-d42f-1509-015eb31fa5b2c1bc010b"
handle = "appointment-booking-v2"
description = "A preact POS UI extension"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
