api_version = "2026-04"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "e9834876-2205-9650-162f-45975a9f3f5395073860"
handle = "esr-product-details-action"
description = "View matched clients for a product drop."

# module: path to the file that contains your extension’s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.tsx"
target = "pos.product-details.action.render"

# You can omit the menu-item target and POS will provide a default menu item for this extension.
# The menu item will present the action target on click.
# This template has the same behavior as the POS-provided default, but is included for completeness.
[[extensions.targeting]]
module = "./src/MenuItem.tsx"
target = "pos.product-details.action.menu-item.render"
